// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsXFN7pJEsVvKEEeJ77QJk1wnxaWU2joQ',
    appId: '1:882974843193:web:6f5e6ec583ac2af3e548e8',
    messagingSenderId: '882974843193',
    projectId: 'plant-disease-detection-f924d',
    authDomain: 'plant-disease-detection-f924d.firebaseapp.com',
    storageBucket: 'plant-disease-detection-f924d.appspot.com',
    measurementId: 'G-2J099969G8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxWn5SUAmSR-VLsY_JSOXD2Zwal7p2bjA',
    appId: '1:882974843193:android:935950b67a499502e548e8',
    messagingSenderId: '882974843193',
    projectId: 'plant-disease-detection-f924d',
    storageBucket: 'plant-disease-detection-f924d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDj3m1p8gCfX8LQTSaCpt0MvcvYaGeYFXM',
    appId: '1:882974843193:ios:b9317bfd35389280e548e8',
    messagingSenderId: '882974843193',
    projectId: 'plant-disease-detection-f924d',
    storageBucket: 'plant-disease-detection-f924d.appspot.com',
    iosClientId: '882974843193-322abd1uehuibj141846khus5ve8i0c8.apps.googleusercontent.com',
    iosBundleId: 'com.example.plantDiseaseDetection',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDj3m1p8gCfX8LQTSaCpt0MvcvYaGeYFXM',
    appId: '1:882974843193:ios:45e99e88bcd173bbe548e8',
    messagingSenderId: '882974843193',
    projectId: 'plant-disease-detection-f924d',
    storageBucket: 'plant-disease-detection-f924d.appspot.com',
    iosClientId: '882974843193-vnm411auk33idg6ltkc5mok4uf9so4m1.apps.googleusercontent.com',
    iosBundleId: 'com.example.plantDiseaseDetection.RunnerTests',
  );
}
